cyberchimps/responsive

.gitpod.dockerfile
=> gitpod configurations 

tests/RespTheme/FooterBottomRowCest.php, tests/_support/Page/RespTheme/FooterBottomRowComponents.php
=> Automation test cases for footer bottom row

tests/RespTheme/FooterMiddleRowCest.php, tests/_support/Page/RespTheme/FooterMiddleRowComponents.php
Please don't merge, have issues.
=> automation test cases for footer middle row

core/includes/customizer/custom-styles.php
=> Fix humberger position mobile

admin/js/responsive-getting-started.js, core/css/lifterlms/lifter_style.css, core/includes/compatibility/lifterlms/class-responsive-lifterlms.php, core/includes/compatibility/lifterlms/customizer/settings/class-responsive-lifterlms-user-dashborad.php, core/includes/customizer/assets/js/lifter-customize-preview.js
=> Lifterlms user dashboard settings and getting started bug in RST.

changelog.txt, core/css/customizer.css, core/includes/customizer/assets/min/css/heading.min.css, core/includes/customizer/assets/min/css/tabs.min.css, core/includes/customizer/controls/heading/heading.css, core/includes/customizer/settings/class-responsive-background-image-customizer.php, core/includes/customizer/settings/class-responsive-page-content-customizer.php, core/includes/customizer/settings/class-responsive-sidebar-layout-customizer.php, core/includes/customizer/settings/class-responsive-site-color-palettes-scheme-customizer.php, core/includes/customizer/settings/class-responsive-typography-customizer.php, core/includes/functions.php, functions.php, package.json, readme.txt, style.css
=> New customizer changes

.github/workflows/pr-code-coverage.yml, .github/workflows/pr-code-sniff.yml, .github/workflows/pr-unit-tests.yml
=> Add more PR checklist files

changelog.txt, functions.php, package.json, readme.txt, style.css
=> Add changelog v5.0.9

core/includes/customizer/custom-styles.php, core/includes/customizer/settings/class-responsive-form-fields-customizer.php
=> Add default value to form fields border width control

core/includes/customizer/assets/js/typography-customize-preview.js, core/includes/customizer/custom-styles.php, core/includes/customizer/customizer.php, core/includes/customizer/helper.php, core/includes/customizer/settings/class-responsive-header-secondary-menu-layouts-customizer.php, core/includes/customizer/settings/class-responsive-typography-customizer.php, core/includes/functions.php, core/sass/_header.scss, functions.php, header.php, partials/header/secondary-navigation.php
=> Created header secondary menu and its customizer

core/includes/customizer/settings/class-responsive-scroll-to-top-customizer.php
=> Arranged the footer customizer > scroll to top into General and Design tabs

admin/templates/getting-started-home.php, core/includes/customizer/helper.php, core/includes/customizer/settings/class-responsive-blog-customizer.php, core/includes/customizer/settings/class-responsive-blog-layout-customizer.php, core/includes/customizer/settings/class-responsive-content-header-layout-customizer.php
=> phase III reported bug fixes

changelog.txt, functions.php, package.json, readme.txt, style.css
=> Add Changelog v5.1.0

partials/header/secondary-navigation.php
=> Fix secondary menu appearing by default issue

admin/templates/getting-started-home.php, core/includes/functions.php
=> Update utm parameters of pricing buttons

core/includes/customizer/custom-styles.php, functions.php
=> Implemented function for typography unit conversion to resolve php warnings

changelog.txt, core/includes/functions-admin.php, core/includes/functions-extensions.php, functions.php, package.json, partials/custom-home/featured-area.php, readme.txt, style.css
=> Changed review notification period and added alt attribute to social icons.

admin/templates/getting-started-home.php, core/includes/customizer/class-responsive-customize-control-checkbox-multiple.php, core/includes/customizer/helper.php, core/includes/customizer/settings/class-responsive-header-secondary-menu-layouts-customizer.php, core/includes/functions.php
=> Upgrade to pro bug

changelog.txt, functions.php, package.json, readme.txt, style.css
=> Updated change log and version number

core/includes/customizer/settings/class-responsive-customizer-notices.php
=> View Pro features visible to pro users resolved

loop-header.php
=> Breadcrumbs visible on home page bug fixed

core/css/customizer.css
=> Minor UI fix

core/css/customizer.css, core/includes/customizer/controls/general.css
=> Fixed bugs during testing

changelog.txt, core/includes/functions.php, functions.php, package.json, readme.txt, style.css
=> Add changelog v6.0.0

core/includes/customizer/settings/class-responsive-scroll-to-top-customizer.php, core/includes/customizer/settings/class-responsive-site-colors-customizer.php
=> Fix UI of Scroll To Top colors and remove site bg color

core/includes/functions-extensions.php
=> Breadrumbs itemListItem bug

sidebar-home.php
=> remove redundant ARIA role from <aside> element

core/includes/customizer/helper.php, core/includes/customizer/settings/class-responsive-header-menu-layouts-customizer.php, core/includes/functions-extras.php, core/includes/functions.php, searchform.php
This option is present in Responsive Pro
=> Search Style option in customizer is missing

core/includes/customizer/extend-controls/src/breadcrumb-toggle.js, core/includes/customizer/extend-controls/src/index.js
=> Fix breadcrumb options are visible even if the breadcrumbs are disabled

core/includes/customizer/controls/imageradiobtn/imageradiobtn.css
=> Fix the layout images

core/includes/customizer/custom-styles.php, core/includes/page-custom-meta.php
=> Fix page width option not working

core/includes/functions-extensions.php, loop-header.php
=> Breadcrumb compatibility issue with yoast seo

changelog.txt, functions.php, package.json, readme.txt, style.css
=> Updated Version Logs for v6.0.2

core/includes/customizer/extend-controls/src/imageradiobtn/imageradiobtn-component.js, core/includes/customizer/extend-controls/src/tabs/tabs-component.js, core/includes/customizer/settings/class-responsive-sidebar-layout-customizer.php
=> WP-6587 Fix: Sidebar toggle buttons not working

core/includes/customizer/controls/builder-available-drag/class-responsive-customizer-builder-available-items-drag-control.php, core/includes/customizer/controls/general.css, core/includes/customizer/customizer.php, core/includes/customizer/extend-controls/src/builder-available-drag/available-drag-component.js, core/includes/customizer/extend-controls/src/builder-available-drag/control.js, core/includes/customizer/extend-controls/src/builder-layout/builder-component.js, core/includes/customizer/extend-controls/src/index.js, core/includes/customizer/settings/class-responsive-footer-layout-customizer.php, core/includes/customizer/settings/hfb-builder/class-responsive-header-footer-builder.php, core/includes/functions.php, functions.php
=> Implement footer builder available items draggable control

core/includes/customizer/settings/hfb-builder/class-responsive-header-footer-builder.php
=> Add Header default choices

admin/templates/getting-started-home.php, core/includes/customizer/assets/js/customize-preview-color-control.js
=> Fix: Docs link of White label, Woocommerce in Dashboard

admin/templates/getting-started-home.php, core/includes/customizer/assets/js/customize-preview-color-control.js, core/includes/customizer/assets/js/customize-preview-image-control.js, core/includes/customizer/custom-styles.php
=> Fix: Global settings overriding sidebar bg color

core/includes/customizer/extend-controls/src/breadcrumb-toggle.js, core/includes/customizer/settings/class-responsive-content-header-layout-customizer.php, core/includes/customizer/settings/class-responsive-panel.php, loop-header.php
=> TASK/WP-6444: Fixed the breadcrumb not showing for page and successfully removed the Enable on Singular option with backward compatibility

changelog.txt, core/includes/customizer/custom-styles.php, functions.php, package.json, readme.txt, style.css
=> WP-6588 - Global settings are overriding the sidebar background color settings - Fixed

core/includes/customizer/assets/js/typography-customize-preview.js, core/includes/customizer/custom-styles.php, core/includes/customizer/settings/class-responsive-typography-customizer.php
=> Fix line height not applying for elementor heading widget

core/includes/customizer/settings/class-responsive-footer-layout-customizer.php, template-parts/footer/footer-row.php
=> Fix theme check warnings

core/includes/customizer/custom-styles.php
=> Fix scroll to top button is not sticky

core/includes/customizer/assets/js/customize-preview-font-presets.js, core/includes/customizer/custom-styles.php, core/includes/customizer/extend-controls/src/fontpresets/fontpreset-component.js, core/includes/customizer/helper.php, core/includes/customizer/settings/class-responsive-site-typography-customizer.php, core/includes/customizer/settings/class-responsive-typography-customizer.php
Task ID: WP-4851
Fix warnings in header, it was accessing the value without checking if it exists or not.
=> WP-4851-Font-Presets Fix warnings in header

core/includes/customizer/custom-styles.php, core/includes/template-functions/header-functions.php, core/sass/woocommerce.scss
=> Fix header cart reported testing issues

core/includes/customizer/custom-styles.php
=> Fix typography not getting applied to the frontend issue

core/includes/customizer/custom-styles.php, core/includes/customizer/settings/class-responsive-typography-customizer.php
Task ID: WP-4851
Font preset changes were different from editor in frontend, over riding other typography, fixed the issue
=> WP-4851 font presets changes were not reflecting

core/includes/functions.php
=> ensure cart color persists after update

core/includes/customizer/helper.php, core/includes/customizer/settings/class-responsive-header-button-customizer.php
=> Fix Button BG color visible in general tab

core/includes/customizer/assets/js/conditional-display-controls.js, core/includes/customizer/assets/js/customize-preview-checkbox-control.js, core/includes/customizer/controls/general.css, core/includes/customizer/settings/class-responsive-header-widgets-customizer.php, core/includes/functions.php, functions.php, sidebar-header.php, template-parts/header/header_widgets1.php
=> Add header widgets as a element with backward compatibility

core/includes/customizer/settings/class-responsive-header-builder-section-customizer.php
=> Remove Header Widgets Redirect Control

core/includes/customizer/settings/class-responsive-header-social-customizer.php
=> Remove unnecessary default

core/includes/customizer/custom-styles.php
=> Make the scroll to top sticky

changelog.txt, functions.php, package.json, readme.txt, style.css
=> Add Change Log v6.1.1

core/includes/customizer/custom-styles.php
=> Fix the Redeclaration fatal error issue

core/includes/customizer/controls/fontpresets/font-presets.css, core/includes/customizer/custom-styles.php, core/includes/customizer/settings/class-responsive-site-typography-customizer.php
Fixed the toggle button not working in mobile view due to button size control Fixed minor UI issues in Font preset control
=> WP-6420 Fix toggle button not visible

changelog.txt, functions.php, package.json, readme.txt, style.css
=> Add changelog v6.1.2

changelog.txt
=> Update changelog v6.1.2

core/includes/customizer/assets/js/customize-preview-drag-number-control.js, core/includes/customizer/controls/builder-row-layout/class-responsive-customizer-builder-row-layout-control.php, core/includes/customizer/custom-styles.php, core/includes/customizer/extend-controls/src/builder-row-layout/row-layout-component.js, core/includes/customizer/extend-controls/src/icons.js, core/includes/customizer/helper.php, core/includes/customizer/settings/hfb-builder/footer/class-responsive-hfb-footer-above-row.php, core/includes/customizer/settings/hfb-builder/footer/class-responsive-hfb-footer-below-row.php, core/includes/customizer/settings/hfb-builder/footer/class-responsive-hfb-footer-primary-row.php, core/sass/_footer.scss, template-parts/footer/footer-row.php
=> Final add responsive options footer rows layout wp 7691

core/includes/functions.php
=> Fix underline issue in html element

core/includes/customizer/extend-controls/src/customizer.js, core/includes/customizer/helper.php, core/includes/customizer/settings/class-responsive-header-contact-info-customizer.php
=> Fix separator not displaying between icon shape and icon style controls

core/includes/functions.php
=> Fix footer rows inner column spacing backward compatibility issue

core/includes/functions.php
=> Fix Header Widgets Issue

core/includes/customizer/settings/class-responsive-header-html-customizer.php
=> Correct the default option

changelog.txt
=> Update changelog v6.1.4

core/includes/customizer/assets/js/conditional-display-controls.js, core/includes/customizer/custom-styles.php, core/includes/customizer/settings/class-responsive-header-menu-layouts-customizer.php, core/includes/customizer/settings/class-responsive-site-colors-customizer.php, core/includes/functions.php
=> Fix scroll to top going out of view WP-8445

changelog.txt, core/includes/customizer/assets/js/customize-preview-select-control.js, core/includes/customizer/custom-styles.php, core/sass/_footer.scss, functions.php, package.json, readme.txt, style.css, template-parts/footer/scroll_to_top.php
=> Fix scroll to top ui bug and add changelog v6.1.5

core/includes/functions.php, functions.php
=> Make the menu background color transparent by default WP-8532,WP-8396

changelog.txt, core/includes/functions.php, functions.php, package.json, readme.txt, style.css
=> Minor bug fix and revert back WP-8532,WP-8396 [e017b25]

admin/js/responsive-getting-started.js, admin/templates/getting-started-home.php, core/includes/customizer/controls/typography/class-responsive-customizer-typography-control.php, core/includes/customizer/controls/typography/typography-weight-control.js
=> Custom fonts card

core/includes/customizer/extend-controls/src/customizer.js, core/includes/customizer/extend-controls/src/tabs/tabs-component.js, core/includes/customizer/helper.php, core/includes/customizer/settings/class-responsive-blog-layout-customizer.php
=> Minor ui fix in blog customizer screen

core/css/customizer.css, core/includes/customizer/assets/min/css/horizontal-separator.min.css, core/includes/customizer/assets/min/css/range.min.css, core/includes/customizer/assets/min/css/toggle.min.css, core/includes/customizer/controls/backgroundimage/class-responsive-customizer-background-image-control.php, core/includes/customizer/controls/color/color.css, core/includes/customizer/controls/fontpresets/font-presets.css, core/includes/customizer/controls/general.css, core/includes/customizer/controls/heading/heading.css, core/includes/customizer/controls/imageradiobtn/imageradiobtn.css, core/includes/customizer/controls/palette/palette.css, core/includes/customizer/controls/redirect/redirect.css, core/includes/customizer/controls/typography/typography.css, core/includes/customizer/extend-controls/src/backgroundimage/responsive-backgound-image-component.js, core/includes/customizer/extend-controls/src/customizer.js, core/includes/customizer/extend-controls/src/typography_group/typography-group-component.js, core/includes/customizer/helper.php, core/includes/customizer/settings/class-responsive-background-image-customizer.php, core/includes/customizer/settings/class-responsive-container-spacing-customizer.php, core/includes/customizer/settings/class-responsive-header-builder-section-customizer.php, core/includes/customizer/settings/class-responsive-sidebar-layout-customizer.php, core/includes/customizer/settings/class-responsive-site-color-palettes-scheme-customizer.php, core/includes/customizer/settings/class-responsive-site-colors-customizer.php, core/includes/customizer/settings/class-responsive-site-typography-customizer.php, loop-header.php
=> Improve the UI of typography and colors customizer panels

changelog.txt, core/includes/functions.php, functions.php, package.json, readme.txt, style.css
=> Add changelog v6.1.8

core/includes/customizer/extend-controls/src/tabs/tabs-component.js
=> Fixed Header builder button element border radius issue

core/includes/compatibility/woocommerce/customizer/settings/class-responsive-woocommerce-shop-layout-customizer.php, core/includes/customizer/custom-styles.php, core/includes/customizer/settings/class-responsive-site-typography-customizer.php
Updates for the following tasks: 
Added Feature : Underline Content Links feature in typography panel (WP-9095)
Bug Fix: Native cart popup options should not appear when toggle button is off (Issue Resolved) (WP-9039)
=> Updates for WP-9095, WP-9039

core/sass/_header.scss
=> Add space between menu child item and arrow

core/includes/functions-sidebar.php, core/includes/functions.php, template-parts/footer/widget-5.php, template-parts/footer/widget-6.php
=> Add Footer Widget 5 and 6

core/includes/customizer/custom-styles.php
=> Fix header button default values

core/includes/customizer/assets/js/customize-preview-color-control.js, core/includes/customizer/custom-styles.php
=> Bug fixes 6.2.1

admin/js/responsive-getting-started.js, admin/templates/getting-started-home.php
Task Link : https://hbwsldeals.nifty.pm/l/gBVb0X8BuTD
=> Wp 9879 bugfixes

admin/js/responsive-getting-started.js, admin/templates/getting-started-home.php, core/includes/customizer/assets/js/customize-preview-color-control.js, core/includes/customizer/assets/js/customize-preview-number-control.js, core/includes/customizer/custom-styles.php, core/includes/customizer/settings/class-responsive-site-layouts-customizer.php
=> Changes 6.2.4 develop rework

core/includes/customizer/assets/min/css/toggle.min.css, core/includes/customizer/controls/heading/heading.css, core/includes/customizer/custom-styles.php, core/includes/customizer/extend-controls/src/customizer.js, core/includes/customizer/extend-controls/src/tabs/tabs-component.js, core/includes/customizer/helper.php, core/includes/customizer/settings/class-responsive-header-transparent-customizer.php, core/includes/customizer/settings/class-responsive-single-blog-layout-customizer.php, core/includes/modules/related-posts/class-responsive-related-posts.php, core/sass/_header.scss, functions.php
=> Fix 6.2.3 testing bugs

core/includes/customizer/settings/class-responsive-single-blog-layout-customizer.php, core/includes/functions.php, core/includes/modules/related-posts/class-responsive-related-posts.php
=> changed default color of related post text and hover

changelog.txt
=> changelog fixes

changelog.txt
=> updating the changelog for 6.2.4

functions.php, template-parts/footer/scroll_to_top.php
=> Theme 6 2 4 rework

core/includes/customizer/assets/js/customize-preview-checkbox-control.js, core/includes/customizer/custom-styles.php, core/includes/customizer/settings/class-responsive-header-layout-customizer.php, core/includes/customizer/settings/class-responsive-panel.php, core/includes/customizer/settings/class-responsive-site-layouts-customizer.php, core/includes/functions.php, functions.php, package.json, readme.txt, style.css, template-parts/header/logo.php
=> Theme 6 2 6 rework

core/includes/customizer/controls/general.css, core/includes/customizer/extend-controls/src/customizer.js
=> Fix hfb builder panel width responsiveness issue
